### ISSUE TITLE
BackEnd

### ISSUE THREAD

**Issue by Julianp1** [Madonahs/GrowWithGoogleTeamProject#14]
Hey Yall,
I'm not sure if you guys have implemented a backend yet but if you haven't firebase is really good at managing HTTP connections, and authenticity. Is it ok if I use firebase or is there a local server you plan to use?

**Comment by emmaunel** [comment]
We do have a local server planned

**Comment by Julianp1** [comment]
Ok, Thank You!

**Comment by Madonahs** [comment]
@Julianp1  welcome to the project yeah we have it ready we have a hangout on how it was done you can join to learn 1 or 2 :)
