### ISSUE TITLE
Add Theme Manager

### ISSUE THREAD

**Issue by MaherSoua** [Madonahs/GrowWithGoogleTeamProject#34]
Creating Theme Manager will help users to configure their application theme.

**Comment by Madonahs** [comment]
This should go on the setting, on the drawer navigator. So that anyone can change it using setting and @emmaunel  is working on it.

**Comment by MaherSoua** [comment]
@emmaunel working on Theme changing?

**Comment by Madonahs** [comment]
Yeah, since you were working on firebase, he was helping with theme , putting it on setting :) But you can chat with him to see whats up.

**Comment by Madonahs** [comment]
@MaherSoua  i am working on this ![screenshot_20180224-190854](https://user-images.githubusercontent.com/11560987/36636936-4eab4950-1996-11e8-9251-61f9c9af610f.png)

**Comment by MaherSoua** [comment]
Sorry but we still have problem I don't see the branch of theme, and also I don't know who is working on what. may be we should do some stand up and do some briefing

**Comment by Madonahs** [comment]
Great, Come to slack  Haha -- you can also brief us on firebase.

**Comment by emmaunel** [comment]
Hi. I'm Emmanuel and I'm the guy working on the theme.

**Comment by MaherSoua** [comment]
@emmaunel can you please open an issue for theme manager and creating a branch ?

**Comment by emmaunel** [comment]
Ok. Will do it when connected to my wifi

**Comment by emmaunel** [comment]
I'm currently using data on my phone and it's slow

**Comment by MaherSoua** [comment]
Ok thank you very much, please we have to work with the same way, 
- Open an issue on github.
- Create your branch on github before starting working, 
don't forget after commit push to your branch , create a pull Request -> add people you want them to do a review and merge to develop

**Comment by MaherSoua** [comment]
@emmaunel I assigned this issue to you like that any team member know that you are working on this :)

**Comment by emmaunel** [comment]
Ok

**Comment by Madonahs** [comment]
@emmaunel  when ready you can let me know we can work on this together :)
