### ISSUE TITLE
[UI] Login button shadow display issue

### ISSUE THREAD

**Issue by MaherSoua** [Madonahs/GrowWithGoogleTeamProject#5]
Buttons for login are not well displayed we can see that the shadow is cut
![image](https://user-images.githubusercontent.com/13171464/36075014-779291fa-0f48-11e8-85f4-529f01224ecb.png)

**Comment by Madonahs** [comment]
I see, we can fix that. Are you working on it now? you can try and push the updates.
![screenshot_20180210-124433](https://user-images.githubusercontent.com/11560987/36075062-7dfca420-0f0e-11e8-9cbc-b2547b21f3d6.jpg)

**Comment by MaherSoua** [comment]
@Madonahs Yes I am working on it, as soon as I finish I will push it :)

**Comment by Madonahs** [comment]
@MaherSoua 👍 that is great, i see what you mean. Great. Thanks.

**Comment by MaherSoua** [comment]
@Madonahs Done :)

**Comment by Madonahs** [comment]
💯 thanks. Let me Pull. @MaherSoua

**Comment by Madonahs** [comment]
@MaherSoua  awesome, looks great.

**Comment by MaherSoua** [comment]
@Madonahs Thanks

**Comment by MaherSoua** [comment]
fixed #5
