### ISSUE TITLE
ProfileFragment 

### ISSUE THREAD

**Issue by Madonahs** [Madonahs/GrowWithGoogleTeamProject#50]
Cannot find annotation method 'value()' in type 'DoNotMock': class file for com.google.errorprone.annotations.DoNotMock not found

UDACITY/GrowWithGoogleTeamProject/app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/ProfileFragment.java uses or overrides a deprecated API.

@CleverChuk  please this does not cause the app to close but we need to figure out whats up.

**Comment by CleverChuk** [comment]
Try cleaning the project and run again. If that does't work, you can wait to run the update

**Comment by Madonahs** [comment]
@CleverChuk  Okay, so any briefs on this uses or overrides a deprecated API. Lol.

**Comment by CleverChuk** [comment]
@Madonahs I don't see that warning on my side. Anyone else getting that warning?

**Comment by Madonahs** [comment]
@CleverChuk  Hey, I think it happens before sync once done it is fine 👍 So closing the issue.
