### ISSUE TITLE
Handling onRotate Bottom Navigation. 

### ISSUE THREAD

**Issue by Madonahs** [Madonahs/GrowWithGoogleTeamProject#56]
Once you Rotate the Bottom Navigator you will notice it jumps back to the main Feeds Fragment we need to handle this such that it can remain on its respective activity on rotate :)

**Comment by radoalbert110** [comment]
what branch is this on @Madonahs ?

**Comment by Madonahs** [comment]
Just check the master. I was checking the master then I noticed.

On Feb 26, 2018 20:48, "Rado RAMBININTSOA" <notifications@github.com> wrote:

what branch is this on @Madonahs <https://github.com/madonahs> ?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Madonahs/GrowWithGoogleTeamProject/issues/56#issuecomment-368728499>,
or mute the thread

**Comment by radoalbert110** [comment]
OK. I see the issue. Will take a look and let you know if I find a fix for it.

**Comment by Madonahs** [comment]
Thank you, noticed it and wrote it down so that i won't forget it. Thanks.

**Comment by Madonahs** [comment]
Fixed :)
